Consider the below code to answer further questions:

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of the variables list_ and array_list.

list_ is a Python list, which is a built-in data type in Python. It can hold elements of different data types.

array_list is a NumPy array, which is a data structure provided by the NumPy library. NumPy arrays are homogeneous, meaning they can only hold elements of the same data type. When you create a NumPy array from a list, the data type of the array is determined by the data type of the elements in the list.

In [4]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
print("Data type of elements in list_:")
for i in list_:
    print(f"Data type of list_ element '{i}': {type(i)}")

print("\nData type of elements in array_list:")
for i in array_list:
    print(f"Data type of array_list element '{i}': {type(i)}")

Data type of elements in list_:
Data type of list_ element '1': <class 'str'>
Data type of list_ element '2': <class 'str'>
Data type of list_ element '3': <class 'str'>
Data type of list_ element '4': <class 'str'>
Data type of list_ element '5': <class 'str'>

Data type of elements in array_list:
Data type of array_list element '1': <class 'numpy.str_'>
Data type of array_list element '2': <class 'numpy.str_'>
Data type of array_list element '3': <class 'numpy.str_'>
Data type of array_list element '4': <class 'numpy.str_'>
Data type of array_list element '5': <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Yes, there will be a difference in the data type of the elements present in list_ and array_list after the specified change.

By specifying dtype = int when creating the NumPy array array_list, you are explicitly instructing NumPy to convert the elements from strings to integers.

In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
print("Data type of elements in list_:")
for i in list_:
    print(f"Data type of list_ element '{i}': {type(i)}")

print("\nData type of elements in array_list:")
for i in array_list:
    print(f"Data type of array_list element '{i}': {type(i)}")

Data type of elements in list_:
Data type of list_ element '1': <class 'str'>
Data type of list_ element '2': <class 'str'>
Data type of list_ element '3': <class 'str'>
Data type of list_ element '4': <class 'str'>
Data type of list_ element '5': <class 'str'>

Data type of elements in array_list:
Data type of array_list element '1': <class 'numpy.int64'>
Data type of array_list element '2': <class 'numpy.int64'>
Data type of array_list element '3': <class 'numpy.int64'>
Data type of array_list element '4': <class 'numpy.int64'>
Data type of array_list element '5': <class 'numpy.int64'>


Consider the below code to answer further questions:

In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [11]:
# (i) Shape
print("Shape of num_array:", num_array.shape)

# (ii) Size
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [16]:
zero_arr = np.zeros([3,3])

zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# (i) Shape
print("Shape of zero_arr:", zero_arr.shape)

# (ii) Size
print("Size of zero_arr:", zero_arr.size)

Shape of zero_arr: (3, 3)
Size of zero_arr: 9


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [18]:
identity_matrix = np.eye(5)

identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Shape
print("Shape of identity_matrix:", identity_matrix.shape)

Shape of identity_matrix: (5, 5)
